/**
 * @file test-reporter.c
 *
 * @brief Test Reporter service implementation.
 *
 * Implements result collection, summary generation,
 * and reporting functionality for test execution
 * results generated by Test Engine.
 */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "test-reporter.h"

static void test_reporter_update_summary(test_summary_t *summary, test_result_t *result) {

    if(summary == NULL || result == NULL) {
        return;
    }
    summary->total_tests++;
    switch(result->state)
    {
        case TEST_STATE_PASS:
            summary->passed_tests++;
            break;
        case TEST_STATE_FAIL:
            summary->failed_tests++;
            break;
        case TEST_STATE_TIMEOUT:
            summary->timeout_tests++;
            break;
        case TEST_STATE_SKIP:
            summary->skipped_tests++;
            break;
        default:
            break;
    }
}
test_reporter_t* test_reporter_init(test_engine_t *test_engine) {

    test_reporter_t *reporter = NULL;
    if(test_engine == NULL) {
        return NULL;
    }

    reporter = (test_reporter_t *)malloc(sizeof(test_reporter_t));
    if(reporter == NULL) {
        return NULL;
    }
    reporter->test_engine = test_engine;
    reporter->result_count = 0;

    memset(&reporter->summary, 0, sizeof(test_summary_t));
    pthread_mutex_init(&reporter->lock, NULL);
    return reporter;
}

int32_t test_reporter_deinit(test_reporter_t *reporter) {

    if(reporter == NULL) {
        return -1;
    }
    pthread_mutex_destroy(&reporter->lock);

    free(reporter);
    return 0;
}

int32_t test_reporter_collect( test_reporter_t *reporter, const char *name){

    test_result_t result;

    if(reporter == NULL || name == NULL) {
        return -1;
    }

    memset(&result, 0, sizeof(test_result_t));

    if(test_engine_get_result( reporter->test_engine, name, &result) != 0) {
        return -1;
    }

    pthread_mutex_lock(&reporter->lock);
    if(reporter->result_count >= TEST_REPORTER_MAX_RESULTS) {
        pthread_mutex_unlock(&reporter->lock);
        return -1;
    }

    memcpy(&reporter->results[reporter->result_count], &result, sizeof(test_result_t));
    reporter->result_count++;

    test_reporter_update_summary(&reporter->summary, &result);

    pthread_mutex_unlock(&reporter->lock);
    return 0;
}

int32_t test_reporter_get_summary(test_reporter_t *reporter, test_summary_t *summary) {

    if(reporter == NULL || summary == NULL) {
        return -1;
    }
    pthread_mutex_lock(&reporter->lock);

    memcpy(summary, &reporter->summary, sizeof(test_summary_t));

    pthread_mutex_unlock( &reporter->lock);

    return 0;
}

int32_t test_reporter_print( test_reporter_t *reporter){

    if(reporter == NULL) {
        return -1;
    }

    pthread_mutex_lock(&reporter->lock);

    printf("\n");
    printf("================================\n");
    printf(" Test Execution Report\n");
    printf("================================\n");

    for(uint32_t index = 0; index < reporter->result_count; index++) {

        test_result_t *result;

        result = &reporter->results[index];

        printf("%-30s : %d\n", result->name, result->state);

    }
    printf("\n");
    printf("Summary\n");
    printf("--------------------------------\n");
    printf("Total   : %u\n", reporter->summary.total_tests);
    printf("Passed  : %u\n", reporter->summary.passed_tests);
    printf("Failed  : %u\n", reporter->summary.failed_tests);
    printf("Timeout : %u\n", reporter->summary.timeout_tests);
    printf("Skipped : %u\n", reporter->summary.skipped_tests);
    printf("================================\n");

    pthread_mutex_unlock(&reporter->lock);

    return 0;
}