/**
 * @file test-reporter.h
 *
 * @brief Test Reporter service interface.
 *
 * This module provides APIs to collect, manage, and
 * report test execution results generated by the
 * Test Engine framework.
 *
 * Test Reporter is responsible for:
 *
 * - Collecting test results
 * - Maintaining execution summary
 * - Providing reporting interface
 *
 * Test Reporter does not access hardware layer,
 * HAL, Device Manager, or Function Manager.
 *
 * Copyright (c) 2026
 */

#ifndef TEST_REPORTER_H
#define TEST_REPORTER_H


#include <stdint.h>
#include <stdbool.h>


#include "test-engine.h"

/**
 * @brief Maximum number of stored test results.
 */
#define TEST_REPORTER_MAX_RESULTS 128

/**
 * @brief Test execution summary.
 *
 * Stores aggregated result information
 * for completed test execution.
 */
typedef struct
{

    /**
     * Total number of executed tests.
     */
    uint32_t total_tests;
    /**
     * Number of passed tests.
     */
    uint32_t passed_tests;
    /**
     * Number of failed tests.
     */
    uint32_t failed_tests;
    /**
     * Number of timeout tests.
     */
    uint32_t timeout_tests;
    /**
     * Number of skipped tests.
     */
    uint32_t skipped_tests;
} test_summary_t;

/**
 * @brief Test Reporter object.
 *
 * Maintains collected test results and
 * execution summary.
 *
 * Thread safety is maintained internally
 * because results can be updated by
 * worker threads.
 */
typedef struct test_reporter_t
{
    /**
     * Reference to Test Engine.
     *
     * Used to retrieve test results.
     */
    test_engine_t *test_engine;

    /**
     * Stored test results.
     */
    test_result_t results[
            TEST_REPORTER_MAX_RESULTS];

    /**
     * Number of stored results.
     */
    uint32_t result_count;

    /**
     * Current execution summary.
     */
    test_summary_t summary;

    /**
     * Reporter synchronization lock.
     */
    pthread_mutex_t lock;
} test_reporter_t;

/**
 * @brief Initialize Test Reporter.
 *
 * Creates reporter instance and initializes
 * internal result storage.
 *
 * @param[in] test_engine
 *        Test Engine instance.
 *
 * @return Test Reporter instance.
 *
 * @retval NULL
 *         Initialization failed.
 */
test_reporter_t* test_reporter_init(
        test_engine_t *test_engine);

/**
 * @brief Deinitialize Test Reporter.
 *
 * Releases resources allocated by
 * Test Reporter.
 *
 * @param[in] reporter
 *        Test Reporter instance.
 *
 * @return Execution status.
 *
 * @retval 0
 *         Success.
 *
 * @retval -1
 *         Invalid parameter.
 */
int32_t test_reporter_deinit(
        test_reporter_t *reporter);

/**
 * @brief Collect test execution result.
 *
 * Fetches result information from
 * Test Engine and updates internal
 * storage and summary.
 *
 * @param[in] reporter
 *        Test Reporter instance.
 *
 * @param[in] name
 *        Test instance name.
 *
 * @return Execution status.
 *
 * @retval 0
 *         Success.
 *
 * @retval -1
 *         Invalid parameter.
 *
 * @retval -2
 *         Result storage full.
 */
int32_t test_reporter_collect(
        test_reporter_t *reporter,
        const char *name);

/**
 * @brief Get test execution summary.
 *
 * Returns aggregated result information.
 *
 * @param[in] reporter
 *        Test Reporter instance.
 *
 * @param[out] summary
 *        Summary output.
 *
 * @return Execution status.
 *
 * @retval 0
 *         Success.
 *
 * @retval -1
 *         Invalid parameter.
 */
int32_t test_reporter_get_summary(
        test_reporter_t *reporter,
        test_summary_t *summary);

/**
 * @brief Print test execution report.
 *
 * Generates human readable report output.
 *
 * @param[in] reporter
 *        Test Reporter instance.
 *
 * @return Execution status.
 *
 * @retval 0
 *         Success.
 */
int32_t test_reporter_print(
        test_reporter_t *reporter);
    
#endif /* TEST_REPORTER_H */