/**
 * @file test_engine.h
 * @brief Test Engine service interface.
 *
 * The Test Engine is responsible for executing validation tests
 * in the Hardware Test Framework.
 *
 * Responsibilities:
 *
 * - Execute validation tests
 * - Manage test lifecycle
 * - Handle setup / execute / cleanup flow
 * - Manage test timeout
 * - Support parallel test execution
 * - Collect execution results
 * - Provide execution context to tests
 *
 * Execution flow:
 *
 * @code
 *
 * Test Engine
 *       |
 *       v
 * Test Instance
 *       |
 *       v
 * Test Context
 *       |
 *       +----------------+
 *       |                |
 *       v                v
 * Function Manager   Device Manager
 *       |
 *       v
 * Device HAL
 *       |
 *       v
 * Plugin
 *       |
 *       v
 * Hardware
 *
 * @endcode
 */

#ifndef TEST_ENGINE_H
#define TEST_ENGINE_H

#include <stdint.h>
#include <stdbool.h>
#include <pthread.h>


#include "test-manager.h"
#include "function-manager.h"
#include "dm.h"

#define MAX_TEST_INSTANCES 128

#define TEST_ENGINE_MAX_WORKERS      8
#define TEST_ENGINE_QUEUE_SIZE       128


/**
 * @brief Test execution state.
 */
typedef enum{
    /**
     * Test is not started.
     */
    TEST_STATE_IDLE = 0,

    /**
     * Test is currently queue.
     */
    TEST_STATE_QUEUED,

    /**
     * Test is currently running.
     */
    TEST_STATE_RUNNING,

    /**
     * Test completed successfully.
     */
    TEST_STATE_PASS,

    /**
     * Test execution failed.
     */
    TEST_STATE_FAIL,

    /**
     * Test execution exceeded timeout.
     */
    TEST_STATE_TIMEOUT,
    /**
     * Test skipped.
     */
    TEST_STATE_SKIP
}test_execution_state_e;

/**
 * @brief Test execution result.
 *
 * Stores the final result generated by the Test Engine.
 */
typedef struct {
    /**
     * Test name.
     */
    char name[TEST_NAME_LENGTH];
    /**
     * Execution state.
     */
    test_execution_state_e state;
    /**
     * Test return value.
     */
    int32_t result;
    /**
     * Execution duration in milliseconds.
     */
    uint32_t execution_time_ms;
    /**
     * Test status message.
     */
    char message[256];
} test_result_t;

/**
 * @brief Test execution context.
 *
 * Provides framework services required by test implementation.
 *
 * Each running test gets its own context to support
 * parallel execution.
 */
typedef struct
{
    /**
     * Device Manager instance.
     */
    device_manager_t *device_manager;
    /**
     * Function Manager instance.
     */
    function_manager_t *function_manager;
    /**
     * Current executing test name.
     */
    char test_name[TEST_NAME_LENGTH];
    /**
     * Maximum execution time.
     */
    uint32_t timeout_ms;
    /**
     * Test start timestamp.
     */
    uint64_t start_time_ms;
}test_context_t;

/**
 * @brief Test callback function.
 *
 * All test lifecycle functions use this interface.
 *
 * @param[in] context Test execution context.
 *
 * @return Test execution status.
 */
typedef int32_t (*test_callback_t)(test_context_t *context);

/**
 * @brief Test lifecycle operations.
 *
 * Defines the complete lifecycle of a test.
 *
 * Execution order:
 *
 * setup()
 *    |
 * execute()
 *    |
 * cleanup()
 */
typedef struct
{
    /**
     * Prepare hardware and resources.
     */
    test_callback_t setup;

    /**
     * Execute validation logic.
     */
    test_callback_t execute;

    /**
     * Release resources.
     */
    test_callback_t cleanup;
} test_operations_t;
/**
 * @brief Registered test entry.
 *
 * Maps a logical test name with its implementation.
 */
typedef struct
{
    /**
     * Test name.
     */
    char name[TEST_NAME_LENGTH];

    /**
     * Test lifecycle callbacks.
     */
    test_operations_t operations;

    /**
     * Maximum allowed execution time.
     */
    uint32_t timeout_ms;
} test_entry_t;






/**
 * @brief Runtime test execution instance.
 *
 * Represents one running test.
 *
 * Multiple instances can execute in parallel.
 */
typedef struct
{

    /**
     * Test definition.
     */
    test_entry_t *entry;


    /**
     * Test execution context.
     */
    test_context_t context;


    /**
     * Test result.
     */
    test_result_t result;

    /**
     * result synchronization lock.
     */
    pthread_mutex_t result_lock;

    /**
     * Indicates test is running.
     */
    bool running;


} test_instance_t;






/**
 * @brief Test Engine runtime object.
 *
 * Manages test execution lifecycle and runtime instances.
 */
typedef struct test_engine_t test_engine_t;


/**
 * @brief Initialize Test Engine.
 *
 * Creates the Test Engine runtime and prepares
 * the execution environment.
 *
 * @param[in] test_manager Test Manager instance.
 * @param[in] function_manager Function Manager instance.
 * @param[in] device_manager Device Manager instance.
 *
 * @return Initialized Test Engine object.
 * @retval NULL Initialization failed.
 */
test_engine_t* test_engine_init(
    test_manager_t *test_manager,
    function_manager_t *function_manager,
    device_manager_t *device_manager);

/**
 * @brief Deinitialize Test Engine.
 *
 * Stops running tests and releases resources.
 *
 * @param[in] test_engine Test Engine instance.
 *
 * @return 0 on success.
 */
int32_t test_engine_deinit(
    test_engine_t *test_engine);

/**
 * @brief Register test implementation.
 *
 * @param[in] test_engine Test Engine instance.
 * @param[in] name Test name.
 * @param[in] operations Test lifecycle operations.
 *
 * @return 0 on success.
 */
int32_t test_engine_register(
    test_engine_t *test_engine,
    const char *name,
    test_operations_t *operations);
/**
 * @brief Execute a single test.
 *
 * Runs:
 *
 * setup()
 * execute()
 * cleanup()
 *
 * with timeout handling.
 *
 * @param[in] test_engine Test Engine instance.
 * @param[in] name Test name.
 *
 * @return 0 on success.
 */
int32_t test_engine_execute(
    test_engine_t *test_engine,
    const char *name);

/**
 * @brief Execute all available tests.
 *
 * Allows parallel execution based on
 * device resource availability.
 *
 * @param[in] test_engine Test Engine instance.
 *
 * @return 0 on success.
 */
int32_t test_engine_execute_all(
    test_engine_t *test_engine);

/**
 * @brief Get test execution result.
 *
 * @param[in] test_engine Test Engine instance.
 * @param[in] name Test name.
 * @param[out] result Test result.
 *
 * @return 0 on success.
 */
int32_t test_engine_get_result(
    test_engine_t *test_engine,
    const char *name,
    test_result_t *result);

#endif /* TEST_ENGINE_H */